name: Maven test
on:
  push:
    branches:
      - main
      - init_tests
      - fix_tests
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '13'
      - run: mvn package
      - uses: actions/upload-artifact@v2
        with:
          name: ProjetJ2E
          path: ./target/ProjetJ2E.jar
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '13'
      - name: Verify tests
        run: mvn clean verify