name: Maven test
on:
  push:
    branches:
      - main
      - init_tests
      - fix_tests
  pull_request:
    branches:
      - main
jobs:
  setup-postgresql-ubuntu:
    if: true # false to skip job during debug
    name: Setup PostgreSQL on Ubuntu
    runs-on: ubuntu-20.04
    steps:
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create scheduler user
        run: |
          sudo -u postgres psql --command="CREATE USER test PASSWORD 'test'" --command="\du"
      - name: Create timetable database
        run: |
          sudo -u postgres createdb --owner=scheduler test
          PGPASSWORD=somestrong psql --username=scheduler --host=localhost --list test
  build:
    needs: setup-postgres-ubuntu
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '13'
      - run: mvn package
      - uses: actions/upload-artifact@v2
        with:
          name: ProjetJ2E
          path: ./target/ProjetJ2E.jar
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '13'
      - name: Verify tests
        run: mvn clean verify