name: Maven test
on:
  - push
jobs:
  run_maven:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '13'
      - run: mvn -v
      - run: mvn help:effective-pom